name: fait
description: Fitness AI Trainer.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  arc_progress_bar_new: ^1.0.4
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  fl_chart: ^0.65.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.6
  flutter_progress_hud: ^2.0.2
  flutter_riverpod: ^2.4.5
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.6
  fluttertoast: ^8.2.4
  image_picker: ^1.0.4
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  liquid_progress_indicator_v2: ^0.5.0
  percent_indicator: ^4.2.3
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  syncfusion_flutter_gauges: ^24.1.45
  table_calendar: ^3.0.9
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600

    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500

    - family: Cairo
      fonts:
        - asset: assets/fonts/CairoRegular.ttf
          weight: 400

    - family: Aquire
      fonts:
        - asset: assets/fonts/Aquire-BW0ox.otf
          weight: 700
        - asset: assets/fonts/AquireLight-YzE0o.otf
          weight: 700
        - asset: assets/fonts/AquireBold-8Ma60.otf
          weight: 700
